# Site settings
title: Adriano's Personal Page
description: Informations about skills, researches, share knowledge, etc.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: http://adrianopereira.github.io

# User settings
username: Adriano Almeida
user_description: Graduated in Computing at Centro Universitário Estácio da Amazônia (2018), where he developed monitoring activities in the programming and database disciplines, also actively participating in programming competitions. Master's student in the Postgraduate Program in Applied Computing at the Brazilian Institute for Space Research (INPE), where he works with computational approaches for extracting information and forecasting severity characteristics in storms, with an emphasis on atmospheric discharges. He has experience with modeling and systems development, relational/non-relational databases, data collection and manipulation. Knowledge in programming languages Python, R, Java, C/C++, SQL, Javascript, PHP and several frameworks and libraries of Data Science, frontend and backend. His main areas of interest are Computer Science, Data Science and Artificial Intelligence applied to Atmospheric Sciences.
user_title: Computer Scientist
email: adriano.almeida@inpe.com
twitter_username: _lordadriano
github_username:  AdrianoPereira
gplus_username:  adrianoalmeida.py

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
